const imagePath = '../Assets/Images/';
const png = '.png';

const Images = {
  languageBg: require(imagePath + 'languageBg' + png),
  welcome: require(imagePath + 'welcome' + png),
  login: require(imagePath + 'login' + png),
  password: require(imagePath + 'password' + png),
  user: require(imagePath + 'user' + png),
  hide: require(imagePath + 'hide' + png),
  facebook: require(imagePath + 'facebook' + png),
  google: require(imagePath + 'google' + png),
  signup: require(imagePath + 'signup' + png),
  forgotPassword: require(imagePath + 'forgotPassword' + png),
  resetPassword: require(imagePath + 'resetPassword' + png),
  lock: require(imagePath + 'lock' + png),
  tick: require(imagePath + 'tick' + png),
  untick: require(imagePath + 'untick' + png),
  tab0: require(imagePath + 'tab0' + png),
  tab1: require(imagePath + 'tab1' + png),
  tab2: require(imagePath + 'tab2' + png),
  bell: require(imagePath + 'bell' + png),
  money: require(imagePath + 'money' + png),
  rightArrow: require(imagePath + 'rightArrow' + png),
  search: require(imagePath + 'search' + png),
  mic: require(imagePath + 'mic' + png),
  npk12: require(imagePath + 'NPK12' + png),
  back: require(imagePath + 'back' + png),
  setting_0: require(imagePath + 'setting_0' + png),
  setting_1: require(imagePath + 'setting_1' + png),
  setting_2: require(imagePath + 'setting_2' + png),
  setting_3: require(imagePath + 'setting_3' + png),
  setting_4: require(imagePath + 'setting_4' + png),
  setting_5: require(imagePath + 'setting_5' + png),
  setting_6: require(imagePath + 'setting_6' + png),
  setting_7: require(imagePath + 'setting_7' + png),
  setting_8: require(imagePath + 'setting_8' + png),
  qr: require(imagePath + 'qr' + png),
};

export default Images;
